# Generated by Django 4.1 on 2022-08-31 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="Creation date"),
                ),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("date", models.DateField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HourlyPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="Creation date"),
                ),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("datetime", models.DateTimeField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
